language: swift
osx_image: xcode8.3
script: fastlane test
xcode_project: SKWebServiceController.xcodeproj
xcode_scheme: SKWebServiceController
after_success:
  - bash <(curl -s https://codecov.io/bash)